apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: sample
spec:
  arches:
  - amd64
  operatingSystems:
  - arch: amd64
    type: linux
    id: ubuntu
    version: "20.04"
    osImage: Ubuntu 20.04.6 LTS
    repository:
      iso:
        localPath: "./ubuntu-20.04-debs-amd64.iso" 
        url:
  kubernetesDistributions:
  - type: kubernetes
    version: v1.23.10
  components:
    helm: 
      version: v3.9.0
    cni: 
      version: v1.2.0
    etcd: 
      version: v3.4.13
    containerRuntimes:
    - type: docker
      #version: 20.10.8
      version: 24.0.6
    docker-compose:
      version: v2.2.2
    crictl: 
      version: v1.24.0
    calicoctl:
      #version: v3.23.2
      version: v3.26.1
    harbor: 
      version: 2.5.3
  images:
  - dockerhub.kubekey.local/library/busybox:latest
  - dockerhub.kubekey.local/library/alpine:3.14
  - dockerhub.kubekey.local/calico/cni:v3.26.1
  - dockerhub.kubekey.local/calico/kube-controllers:v3.26.1
  - dockerhub.kubekey.local/calico/node:v3.26.1
  - dockerhub.kubekey.local/calico/pod2daemon-flexvol:v3.26.1 
  - dockerhub.kubekey.local/coredns/coredns:1.8.6
  - dockerhub.kubekey.local/csiplugin/snapshot-controller:v4.0.0
  - dockerhub.kubekey.local/jimmidyson/configmap-reload:v0.7.1
  - dockerhub.kubekey.local/kubesphere/kube-events-ruler:v0.6.0
  - dockerhub.kubekey.local/kubesphere/kube-events-operator:v0.6.0
  - dockerhub.kubekey.local/kubesphere/nginx-ingress-controller:v1.3.1
  - dockerhub.kubekey.local/kubesphere/license-server:7900b04
  - dockerhub.kubekey.local/kubesphere/prometheus-operator:v0.55.1
  - dockerhub.kubekey.local/kubesphere/pause:3.6
  - dockerhub.kubekey.local/kubesphere/prometheus-config-reloader:v0.55.1
  - dockerhub.kubekey.local/kubesphere/notification-manager:v2.3.0
  - dockerhub.kubekey.local/kubesphere/notification-manager-operator:v2.3.0
  - dockerhub.kubekey.local/kubesphere/notification-tenant-sidecar:v3.2.0
  - dockerhub.kubekey.local/kubesphere/log-sidecar-injector:v1.2.0
  - dockerhub.kubekey.local/kubesphere/metrics-server:v0.4.2
  - dockerhub.kubekey.local/kubesphere/ks-installer:v3.4.0
  - dockerhub.kubekey.local/kubesphere/kube-apiserver:v1.23.10
  - dockerhub.kubekey.local/kubesphere/kube-auditing-operator:v0.2.0
  - dockerhub.kubekey.local/kubesphere/kube-auditing-webhook:v0.2.0
  - dockerhub.kubekey.local/kubesphere/kube-controller-manager:v1.23.10
  - dockerhub.kubekey.local/kubesphere/kubectl:v1.22.0
  - dockerhub.kubekey.local/kubesphere/kube-proxy:v1.23.10
  - dockerhub.kubekey.local/kubesphere/kube-rbac-proxy:v0.11.0
  - dockerhub.kubekey.local/kubesphere/kube-scheduler:v1.23.10
  - dockerhub.kubekey.local/kubesphere/kube-state-metrics:v2.6.0
  - dockerhub.kubekey.local/kubesphere/fluent-bit:v1.9.4
  - dockerhub.kubekey.local/kubesphere/fluentbit-operator:v0.14.0
  - dockerhub.kubekey.local/kubesphere/k8s-dns-node-cache:1.15.12
  - dockerhub.kubekey.local/library/redis:6.2.6-alpine
  - dockerhub.kubekey.local/library/redis:5.0.14-alpine
  - dockerhub.kubekey.local/library/busybox:latest
  - dockerhub.kubekey.local/library/minio:2023.3.27
  - dockerhub.kubekey.local/minio/mc:RELEASE.2019-08-07T23-14-43Z
  - dockerhub.kubekey.local/minio/minio:RELEASE.2019-08-07T01-59-21Z
  - dockerhub.kubekey.local/mirrorgooglecontainers/defaultbackend-amd64:1.4
  - dockerhub.kubekey.local/openebs/linux-utils:3.3.0
  - dockerhub.kubekey.local/openebs/provisioner-localpv:3.3.0
  - dockerhub.kubekey.local/osixia/openldap:1.3.0
  - dockerhub.kubekey.local/prom/alertmanager:v0.23.0
  - dockerhub.kubekey.local/prom/node-exporter:v1.3.1
  - dockerhub.kubekey.local/prom/prometheus:v2.39.1
  - dockerhub.kubekey.local/thanosio/thanos:v0.31.0
  - dockerhub.kubekey.local/kubesphere/ks-apiserver:v3.4.0
  - dockerhub.kubekey.local/kubesphere/ks-console:v3.4.0
  - dockerhub.kubekey.local/kubesphere/ks-controller-manager:v3.4.0
  - dockerhub.kubekey.local/library/haproxy:2.3
  registry:
    auths: {}
